language: java
jdk:
  - openjdk11
before install:
  - chmod +x mvnw
  - psql -c "CREATE USER root WITH PASSWORD 'root' CREATEDB;" -U postgres
services:
  - postgresql
script:
  - mvn clean install
cache:
  directories:
    - $HOME/.m2
