version: "3"
services:
  postgres:
    image: postgres
    container_name: postgres
    ports:
    - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=root
      - POSTGRES_DB=postgres
  app:
    container_name: spring-boot-project
    image: spring-boot-project
    build: ./
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres
